apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane-api
  namespace: ai-platform
  labels:
    app.kubernetes.io/name: control-plane-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: control-plane-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: control-plane-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
    spec:
      automountServiceAccountToken: false
      containers:
        - name: api
          image: ghcr.io/lolupapi/ai-control-plane:latest
          imagePullPolicy: Always
          env:
            - name: AICP_MODE
              value: mock          # switch to "llm" to route through LiteLLM
            - name: LITELLM_BASE_URL
              value: http://litellm.ai-platform.svc.cluster.local:4000/v1
            - name: LITELLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: litellm-secrets
                  key: LITELLM_MASTER_KEY
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: control-plane-api
  namespace: ai-platform
  labels:
    app.kubernetes.io/name: control-plane-api
spec:
  selector:
    app.kubernetes.io/name: control-plane-api
  ports:
    - name: http
      port: 8080
      targetPort: http
